### ISSUE TITLE
shulker boxes not placing the right way from dispensers

### ISSUE THREAD

**Issue by RTFEEL** [jimbot6000/Block-Entity-Extended-Rendering#12]
when a shulker box is placed via a dispenser it does not face the correct direction. it always faces upwards instead of in the direction the dispenser is facing. I'm unsure if it is because of the mods I am using but here is a list.
1.20:
block-entity-extended-rendering-3.0.0
carpet-extra-1.20-1.4.115
cmdkeybind-1.6.3-1.20
fabric-api-0.83.0+1.20
fabric-carpet-1.20-1.4.112+v230608
indium-1.0.18+mc1.20
iris-mc1.20-1.6.4
modmenu-7.0.1
sodium-fabric-mc1.20-0.4.10+build.27
worldedit-mod-7.2.15

**Comment by jhalfsharp** [comment]
This might not be a bug at all. In the vanilla game, shulker boxes only face in the direction the dispenser does when there is no block below them. When there is, they always face upwards. Test whatever you're doing in a vanilla game to see if anything is actually different.

If there actually is a bug going on, try disabling mods one at a time to determine which one is causing your issue. Until you've narrowed it down to specifically this mod, I have no reason to think that this is the one causing the problem, especially since I shouldn't be touching any of the code related to that.

Please make sure there actually is a bug, and that it is actually a bug in this specific mod, before opening an issue in the future. Thanks!
