### ISSUE TITLE
Banners or mob/player heads

### ISSUE THREAD

**Issue by BangDroid** [jimbot6000/Block-Entity-Extended-Rendering#15]
I have EBE but I found it doesn't do banners or heads.
I am just wanting to confirm BEER will compliment EBE with banners.
What about heads?

**Comment by jhalfsharp** [comment]
https://tryitands.ee/

BEER will, in fact, work with banners; that's why I made it.
I have not tested heads; unless they override the function to get render distance, though, BEER should work with them too. The only rendered items that override the functions are things like beacon beams and books on enchanting tables.
